version: '3.1'
services:
  app:
    build:
      context: node
    networks:
      desafio_net:
    ports:
      - 3000:3000
    entrypoint: wait-for database:3306 -t 30 -- ./start.sh
    depends_on:
      - database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: node_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      desafio_net:
    volumes:
      - ./data:/var/lib/mysql
  nginx:
    build:
      context: nginx
    networks:
      desafio_net:
    ports:
      - 8080:80
networks:
  desafio_net:
    driver: bridge